{
 "title": "k6 dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(k6_data_sent_total[$__rate_interval]))"
    },
    {
     "expr": "sum(rate(k6_data_received_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "rate(k6_http_reqs_total[$__rate_interval])",
     "legendFormat": "{{name}} - {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k6_http_req_duration_p99",
     "legendFormat": "{{name}} - {{method}} {{status}}"
    }
   ]
  }
 ]
}